version: '3.8'

services:
  frontend:
    build:
      context: ./courses_frontend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:8000

  backend:
    build:
      context: ./CoursesAPI
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=courses_api.settings
      - DJANGO_ALLOWED_HOSTS=localhost
    volumes:
      - ./CoursesAPI:/usr/src/app
